name: "Flyway Migrate"
description: "Execute the migrate command using the flyway CLI"
inputs:
  url:
    description: "JDBC URL for the database to migrate"
    required: false
  user:
    description: "Username to login to the database"
    required: false
  password:
    description: "Password to login to the database"
    required: false
  locations:
    description: "Comma-separated list of locations to scan recursively for migrations"
    required: false
  extraArgs:
    description: "Extra arguments to pass to Flyway that aren't specified by this GitHub Action. See https://documentation.red-gate.com/fd/parameters-224919673.html for possible options."
    required: false
    default: ""

runs:
  using: docker
  image: docker://redgate/flyway:latest-alpine
  env:
    FLYWAY_URL: ${{ inputs.url }}
    FLYWAY_USER: ${{ inputs.user }}
    FLYWAY_PASSWORD: ${{ inputs.password }}
    FLYWAY_LOCATIONS: ${{ inputs.locations }}
  args:
    - migrate
    - ${{ inputs.extraArgs }}
    - -X
